# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON c:\Users\vikra\Desktop\embedded\doom_stm\DOOM_STM

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32L476xx>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32L476xx>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L4xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L4xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32L4xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L4xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L4xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32L4xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32L476RGTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32L476RGTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "Core\\Src\\main.c"
    "Core\\Src\\stm32l4xx_hal_msp.c"
    "Core\\Src\\stm32l4xx_it.c"
    "Core\\Src\\syscalls.c"
    "Core\\Src\\sysmem.c"
    "Core\\Src\\system_stm32l4xx.c"
    "Core\\Startup\\startup_stm32l476rgtx.s"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_adc_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_adc.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_cortex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_dma_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_dma.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_exti.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_flash_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_flash_ramfunc.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_flash.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_gpio.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_pwr_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_pwr.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_rcc_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_rcc.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_spi_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_spi.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_tim_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_tim.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_uart_ex.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal_uart.c"
    "Drivers\\STM32L4xx_HAL_Driver\\Src\\stm32l4xx_hal.c"
    "DOOM-master\\DOOM-master\\ipx\\DOOMNET.C"
    "DOOM-master\\DOOM-master\\ipx\\IPXNET.C"
    "DOOM-master\\DOOM-master\\ipx\\IPXSETUP.C"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\am_map.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\d_items.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\d_main.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\d_net.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\doomdef.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\doomstat.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\dstrings.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\f_finale.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\f_wipe.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\g_game.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\hu_lib.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\hu_stuff.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\i_main.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\i_net.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\i_sound.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\i_system.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\i_video.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\info.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_argv.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_bbox.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_cheat.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_fixed.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_menu.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_misc.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_random.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\m_swap.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_ceilng.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_doors.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_enemy.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_floor.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_inter.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_lights.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_map.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_maputl.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_mobj.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_plats.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_pspr.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_saveg.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_setup.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_sight.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_spec.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_switch.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_telept.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_tick.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\p_user.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_bsp.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_data.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_draw.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_main.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_plane.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_segs.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_sky.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\r_things.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\s_sound.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\sounds.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\st_lib.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\st_stuff.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\tables.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\v_video.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\w_wad.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\wi_stuff.c"
    "DOOM-master\\DOOM-master\\linuxdoom-1.10\\z_zone.c"
    "DOOM-master\\DOOM-master\\sersrc\\DOOMNET.C"
    "DOOM-master\\DOOM-master\\sersrc\\PORT.C"
    "DOOM-master\\DOOM-master\\sersrc\\SERSETUP.C"
    "DOOM-master\\DOOM-master\\sndserv\\linux.c"
    "DOOM-master\\DOOM-master\\sndserv\\sounds.c"
    "DOOM-master\\DOOM-master\\sndserv\\soundsrv.c"
    "DOOM-master\\DOOM-master\\sndserv\\wadread.c"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()